{
 "title": "Minitwit Example Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"minitwit:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of HTTP respons",
   "type": "timeseries",
   "description": "rate(minitwit_http_responses_total[$__rate_interval])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(minitwit_http_responses_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "minitwit_http_responses_total", "legendFormat": "Total Message Posts" }
   ]
  },
  {
   "title": "Http response total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_http_responses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU load percent",
   "type": "stat",
   "description": "minitwit_cpu_load_percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_cpu_load_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}