name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: python -m pytest tests/test_sanity.py